/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Command": {                                     "en": "Command",                                         "de": "Befehl",                                          "ru": "команда",                                         "pt": "Comando",                                         "nl": "Commando",                                        "fr": "Commander",                                       "it": "Comando",                                         "es": "Mando",                                           "pl": "Komenda",                                         "zh-cn": "命令"},
    "IP": {                                          "en": "IP",                                              "de": "IP",                                              "ru": "IP",                                              "pt": "IP",                                              "nl": "IK P",                                            "fr": "IP",                                              "it": "IP",                                              "es": "IP",                                              "pl": "IP",                                              "zh-cn": "知识产权"},
    "Name": {                                        "en": "Name",                                            "de": "Name",                                            "ru": "имя",                                             "pt": "Nome",                                            "nl": "Naam",                                            "fr": "Nom",                                             "it": "Nome",                                            "es": "Nombre",                                          "pl": "Imię",                                            "zh-cn": "名称"},
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "Port": {                                        "en": "Port",                                            "de": "Port",                                            "ru": "порт",                                            "pt": "Porta",                                           "nl": "Port",                                            "fr": "Port",                                            "it": "Porta",                                           "es": "Puerto",                                          "pl": "Port",                                            "zh-cn": "港口"},
    "User": {                                        "en": "User",                                            "de": "Benutzer",                                        "ru": "пользователь",                                    "pt": "Do utilizador",                                   "nl": "Gebruiker",                                       "fr": "Utilisateur",                                     "it": "Utente",                                          "es": "Usuario",                                         "pl": "Użytkownik",                                      "zh-cn": "用户"},
    "shellaction adapter settings": {                "en": "Adapter settings for shell action",               "de": "Adaptereinstellungen für Shell Action",           "ru": "Настройки адаптера для shellaction",              "pt": "Configurações do adaptador para shellaction",     "nl": "Adapterinstellingen voor shellaction",            "fr": "Paramètres d'adaptateur pour shellaction",        "it": "Impostazioni dell'adattatore per shellaction",    "es": "Ajustes del adaptador para shellaction",          "pl": "Ustawienia adaptera dla shellaction",             "zh-cn": "shellaction的适配器设置"},
    "IP Address": {                                  "en": "IP Address",                                      "de": "IP Adresse",                                      "ru": "Айпи адрес",                                      "pt": "Endereço de IP",                                  "nl": "IP adres",                                        "fr": "Adresse IP",                                      "it": "Indirizzo IP",                                    "es": "Dirección IP",                                    "pl": "Adres IP",                                        "zh-cn": "IP地址"},
};